tradingstrategy-ai/trading-strategy

tests/test_client.py, tradingstrategy/timebucket.py
Towards https://github.com/tradingstrategy-ai/oracle/issues/32
We need additional time buckets to better support all upcoming token stats
=> Expand TimeBucket enum with new members

tradingstrategy/environment/jupyter.py
There was an *if* missing which meant all downloads warned
=> fix erroneous warning in notebook download

tests/test_candle_universe.py, tradingstrategy/client.py, tradingstrategy/transport/cache.py
Closes https://github.com/tradingstrategy-ai/trade-executor/issues/14
This PR improves the following:
- If a corrupted parquet file is detected, only that file is purged,
not the entire cache.
- We do not sleep unnecessarily after the last failed download attempt
- When we give up on retrying, we still clean the corrupted file,
so that any next runs do not hit an unnecessary error on first
attempt
- Fixed the retry count logic, we now actually raise the last
exception during the last attempt instead of silently returning None
=> Improve failed parquet download retries

.github/workflows/pip-install.yml, .github/workflows/python-app.yml, tests/transport/test_cache.py, tradingstrategy/transport/cache.py
Closes #21.
This PR changes the candle data cache invalidation logic - if there is an end time specified, such file never expires.
=> Never expire cached candle files with end time

tests/test_pair_universe.py, tests/test_stablecoin.py, tradingstrategy/exchange.py, tradingstrategy/pair.py
* Change value `uni_v2` -> `uniswap_v2` for clarity
* Change value `uni_v3` -> `uniswap_v3` for clarity
* Keep `uni_v2` value but marked as deprecated and write a note
* Remove `PairType` as it's duplicated of `ExchangeType`
=> Update ExchangeType enum

tradingstrategy/environment/jupyter.py
Closes https://github.com/tradingstrategy-ai/backend/issues/81
A trading strategy notebook user cannot do much about it anyway, and we already have a decent fallback in place, i.e. displaying the "content length unknown" title on the progress bar.
=> Remove the "no Content-Length header" warning

tradingstrategy/exchange.py
Towards https://github.com/tradingstrategy-ai/oracle/issues/176
As per requirements, a new exchange type is needed, but the corresponding enum is defined here, not in oracle.
=> Add Uniswap v2 incompatible exchange type

CHANGELOG.md, poetry.lock, pyproject.toml, tests/mock_client/test_uniswap_v2_mock_client.py, tests/test_pair_universe.py, tradingstrategy/exchange.py, tradingstrategy/pair.py, tradingstrategy/testing/mock_client.py, tradingstrategy/testing/uniswap_v2_mock_client.py
- Designed for testing EVM backends
- Do not download datasets from oracle, but generate them in-fly from on-chain events
- Makes building live testing strategies easier
=> Add mock Client

CHANGELOG.md, tradingstrategy/candle.py, tradingstrategy/pair.py, tradingstrategy/utils/groupeduniverse.py
- small PR that can more than halve backtesting time
- caches candles by pair id instead of fetching them using expensive pandas methods
=> add optimization

CHANGELOG.md, tests/mock_client/test_uniswap_v2_mock_client.py, tradingstrategy/exchange.py, tradingstrategy/testing/mock_client.py, tradingstrategy/testing/uniswap_v2_mock_client.py
- refactor some common code from `GenericMockClient` and `UniswapV2MockClient` into `MockClient`
- Note: `GenericMockClient` resides in Tradeexecutor due to its reliance on certain imports
=> Refactor mock client

CHANGELOG.md, tradingstrategy/transport/jsonl.py
Uniswap v3 data still uses volume instead of buy/sell volume, so undeprecate
=> update candle mapping (undeprecate volume)

CHANGELOG.md, tradingstrategy/candle.py, tradingstrategy/client.py, tradingstrategy/lending.py, tradingstrategy/utils/groupeduniverse.py
- Fix `estimate_accrued_interest` crashing when there are gaps in data
- Fix `resample_candles` to retain `pair_id` column if one is present in data
=> Correctly handle lending data gaps in Aave

CHANGELOG.md, scripts/fetch-binance-candles.py, tests/test_binance_data.py, tradingstrategy/binance_data.py
- Add: `BinanceDownloader.fetch_approx_asset_trading_start_date()` to figure out when asset was listed on Binance
- Fix: `BinanceDownloader` timestamps to be UTC
- Add: Example script how to download Binance data for multiple assets and write in a single Parquet file
=> Add Binace asset trade start date fetcher

tests/test_lending.py, tradingstrategy/client.py
- Currently, lending candles only support a minimum granularity of 1 hour. This PR allows arbitrary granularity by upsampling
- Also changes `USDC` to `USDC.e` in tests
=> allow for less granular candles

.github/workflows/python-app.yml, tests/test_binance_data.py, tradingstrategy/binance/downloader.py
Use env var to be able to override default Binance API urls
=> Override default binance urls

CHANGELOG.md, tests/test_binance_data.py, tradingstrategy/candle.py, tradingstrategy/client.py, tradingstrategy/transport/cache.py
- Having pd.MultiIndex instead of per-pair pd.DateTimeIndex on candles slows down price access on backtesting considerably
- Backtesting is fast after this patch
=> Avoid pd.MultiIndex on OHLCV data

CHANGELOG.md, tests/test_candle_data.py, tradingstrategy/candle.py, tradingstrategy/utils/forward_fill.py, tradingstrategy/utils/wrangle.py
- Add: `forward_fill(forward_fill_until)`
- The default behavior is to forward fill gaps between first and last candle
- However the last candle might not be updated if we load live sparse data and there has been no trades (no candles)
- Force the forward fill to go until a certain timestamp
=> Add forward_fill_until to deal with gaps of rarely traded live pairs

pyproject.toml, tests/test_liquidity_universe.py, tests/test_top_pairs.py, tradingstrategy/alternative_data/coingecko.py, tradingstrategy/environment/base.py, tradingstrategy/liquidity.py, tradingstrategy/transport/cache.py, tradingstrategy/utils/logging_retry.py
- Use `requests` timeout tuple
- USe `LoggableRetry` adapter instead of default `Retry`
- `/top` endpoint updates and changes to make HTTP replies smaller
=> Improve retry and timeout for HTTP JSON endpoints

tests/test_tvl.py, tradingstrategy/token_metadata.py, tradingstrategy/utils/token_extra_data.py
- TokenSniffer reply can be None when TokenSniffer has internal issues
=> Handle TokenSniffer errors more gracefully

tests/test_aggregate_ohlcv.py, tests/test_candle_universe.py, tests/test_liquidity_universe.py, tradingstrategy/pair.py, tradingstrategy/utils/forward_fill.py, tradingstrategy/utils/groupeduniverse.py, tradingstrategy/utils/liquidity_filter.py
- Rewrite OHCLV `forward_fill_until` logic
- Add a boolean marker to tell when the pair data was forward-filled, as `forward_filled` column in DataFrame
- We will retain the information what data originally was raw and not forward filled
- Useful for alerts, etc.
=> Rerwrite OHLCV forward fill to support forward_filled=True column
