- docs/source/index.rst
Assuming you want to use past tense here
> Small typo fix

- README.md
- docs/source/algo-creators.rst
- docs/source/glossary.rst
- docs/source/investors.rst
- docs/source/programming/algorithms/ape-in.ipynb
- docs/source/programming/algorithms/double-7-advanced.ipynb
- docs/source/programming/algorithms/double-7.ipynb
- docs/source/programming/algorithms/entropy-monkey.ipynb
- docs/source/programming/algorithms/pancakeswap-momentum-liquidity-aware.ipynb
- docs/source/programming/algorithms/pancakeswap-momentum-naive.ipynb
- docs/source/programming/datasets.rst
- docs/source/programming/development.rst
- docs/source/programming/examples/fastquant.ipynb
- docs/source/programming/examples/getting-started.ipynb
- docs/source/programming/examples/interactive-charts.ipynb
- docs/source/programming/examples/liquidity-analysis.ipynb
- docs/source/programming/examples/pairs.ipynb
- docs/source/programming/examples/plotting.ipynb
- docs/source/programming/examples/pool-liquidity.ipynb
- docs/source/programming/examples/price-impact.ipynb
- docs/source/programming/examples/technical-analysis.ipynb
- docs/source/programming/internal-id.rst
- docs/source/programming/learn.rst
- docs/source/programming/referenceprice.rst
- docs/source/programming/release-notes.rst
- docs/source/programming/running.rst
- docs/source/programming/tracking.rst
- docs/source/programming/troubleshooting.rst
- docs/source/protocol/comparison.rst
- docs/source/protocol/overview.rst
After going through the [Getting Started](https://tradingstrategy.ai/docs/programming/examples/getting-started.html) tutorial, I noticed some unpolished bits in the docs, which this PR attempts to fix.
> Misc. fixes in the docs

- CHANGELOG.md
- poetry.lock
- pyproject.toml
- tests/test_candle_universe.py
- tradingstrategy/candle.py
- tradingstrategy/client.py
- tradingstrategy/pair.py
- tradingstrategy/reader.py
- tradingstrategy/transport/cache.py
- tradingstrategy/transport/jsonl.py
- Offer an option to load Parquet files with filtering (not used)
- Load candles data over new JSONL endpoint
> Low memory optimisations

- tests/test_backtrader_integration.py
- tests/test_candle_universe.py
- tests/test_double_7.py
- tests/test_liquidity_universe.py
- tests/test_price_impact.py
- tests/test_qstrader.py
Our latest version of the tests took [26-27mins to complete](https://github.com/tradingstrategy-ai/trading-strategy/actions/runs/2895819196), this PR is to fix that
> Faster tests

- tests/test_candle_data.py
- tradingstrategy/candle.py
`get_price_with_tolerance`  Code debugging
> `get_price_with_tolerance` edits for `candle_timestamp`

- CHANGELOG.md
- tradingstrategy/utils/summarydataframe.py
See https://github.com/tradingstrategy-ai/trade-executor/pull/139
> change candles to bars

- CHANGELOG.md
- tests/test_pair_universe.py
- tradingstrategy/pair.py
Add a way to easily resolve multiple trading pairs using human descriptions
> Human readable pair description

- CHANGELOG.md
- scripts/liquidity-iterator-speed-test.py
- tests/test_resampled_liquidity_universe.py
- tradingstrategy/direct_feed/ohlcv_aggregate.py
- tradingstrategy/liquidity.py
- tradingstrategy/pair.py
- tradingstrategy/universe.py
- tradingstrategy/utils/groupeduniverse.py
- Fast
- Add a method to test different liquidity data access speed
> Add ResampledLiquidityUniverse

- tests/test_caip.py
- tradingstrategy/chain.py
Close https://github.com/tradingstrategy-ai/oracle/issues/305
> Add Arbitrum to ChainId

- CHANGELOG.md
- pyproject.toml
- tests/test_pair_universe.py
- tradingstrategy/pair.py
- Add a human-friendly get_pair()
- Hopefully this is the last get_pair() function I need to write
> Add polished get_pair()

- CHANGELOG.md
- tests/test_candle_universe.py
- tradingstrategy/pair.py
- tradingstrategy/utils/groupeduniverse.py
Makes writing technical indicators easier.
> Adding get_last_entries_by_pair_and_timestamp() and fixes

- CHANGELOG.md
- poetry.lock
- tests/test_pair_universe.py
- tradingstrategy/pair.py
- Better filter in dataframe using chain id and exchange slug
- If pair ticker specifies fee, e.g: ("WETH", "USDC", 5) then use the fee for filtering as well
- Change hardcoded buy volume sorting criteria to be function argument for more flexible filtering
> Improve resolve pairs

- CHANGELOG.md
- tests/test_client.py
- tradingstrategy/client.py
- tradingstrategy/transport/cache.py
Closes #67 
Towards https://github.com/tradingstrategy-ai/oracle/issues/292
> Add a method for downloading reserves data

- CHANGELOG.md
- tradingstrategy/charting/candle_chart.py
Very small bugfix for validating ohlcv data from the API
> change required_columns

- CHANGELOG.md
- tests/test_caip.py
- tradingstrategy/charting/candle_chart.py
- tradingstrategy/utils/groupeduniverse.py
- Silencing warning given by pandas in `PairGroupedUniverse.get_pair_ids()`
- Fixes failing test broken by previous commit
> Silence warning

- tradingstrategy/charting/candle_chart.py
> Add comment

- tradingstrategy/charting/candle_chart.py
- small bug fix for detached indicators
> fix none type bug

- CHANGELOG.md
- tests/test_charting.py
- tradingstrategy/charting/candle_chart.py
- fixes bugs for different `volume_bar_modes`
- adds support for different subtitle font sizes
- adds tests to make to catch charting bugs earlier in the future
Needs to be merged and released before https://github.com/tradingstrategy-ai/trade-executor/pull/271
> Detached indicator bug fix + tests

- CHANGELOG.md
- tests/test_charting.py
- tradingstrategy/charting/candle_chart.py
- Chart visualization fixes
- remove `price_chart_rel_size` and `subplot_rel_size` options (will all be specified in `relative_sizing`)
- refactor and clean code in `tradingstrategy/charting/candle_chart.py`
- See https://github.com/tradingstrategy-ai/trade-executor/pull/291 for more details
- Merge and release required before https://github.com/tradingstrategy-ai/trade-executor/pull/291 can be merged
> Visual fix 2

- CHANGELOG.md
- pyproject.toml
- tests/test_pair_universe.py
- tradingstrategy/pair.py
- tradingstrategy/types.py
- Make sure different fee tiers are resolved correctly
- Default to the lowest fee tier if fee tier is not specified
> Resolve multiple fees

- CHANGELOG.md
- tests/test_candle_universe.py
- tradingstrategy/utils/groupeduniverse.py
release required before https://github.com/tradingstrategy-ai/trade-executor/pull/300 can be merged
> change `resample_candles` to use timedelta

- tradingstrategy/candle.py
- tradingstrategy/transport/jsonl.py
Part of https://github.com/tradingstrategy-ai/oracle/issues/289
> Add volume field to Candle dataclass

- CHANGELOG.md
- tests/test_pair_universe.py
- tradingstrategy/pair.py
- tradingstrategy/types.py
- Add a DataFrame helper that can generate base_token_address and quote_token_address columns
> Add base_token_address and quote_token_address column

- CHANGELOG.md
- tests/direct_feed/test_filter_wick.py
- tests/test_candle_universe.py
- tradingstrategy/candle.py
- tradingstrategy/direct_feed/candle_feed.py
- tradingstrategy/direct_feed/synthetic_feed.py
- tradingstrategy/utils/groupeduniverse.py
- Add: `tradingstrategy.utils.groupeduniverse.fix_bad_wicks` to deal with candle data where high and low
values are abnormal due to various price manipulation issues. 
- Update: Automatically filter bad wicks when creating a candle universe
> Adding wick filter

- CHANGELOG.md
- tradingstrategy/pair.py
- tradingstrategy/testing/uniswap_v2_mock_client.py
- tradingstrategy/utils/groupeduniverse.py
- `get_single_pair_data()` was found to behave confusingly in the beta testing
> Better error message in the data unavailability for get_single_pair_data()

- CHANGELOG.md
- tests/test_liquidity_universe.py
- tradingstrategy/candle.py
- Optimisation: `get_price_with_tolerance()`:  candle price lookup is 40x faster for exact timestamp matches
- Fix liquidity test as the current market liquidity has been going down
> Fast fast price lookup

- CHANGELOG.md
- tests/test_candle_data.py
- tradingstrategy/candle.py
- tradingstrategy/utils/forward_fill.py
- tradingstrategy/utils/groupeduniverse.py
- Optimisation: `get_price_with_tolerance()`: 
candle price lookup is much faster with sparse data match
- Added `trading_strategy.utils.forward_fill` module for 
dealing with sparse data
> Candle data forward fill support, faster sparse data lookups

- tests/test_charting.py
- Adds tests for candle rounding
- Fixes #96
> add tests for candle rounding

- tradingstrategy/pair.py
- tradingstrategy/testing/uniswap_v2_mock_client.py
- Related to https://github.com/tradingstrategy-ai/trade-executor/pull/382
- Merge and release required
> add multipair support for perform-test-trade

- CHANGELOG.md
- tradingstrategy/pair.py
- Workaround pair data issues when Parquest is interpreting some values as NaN when should be None
- Might be related to Parquest data format and somehow values get misinterpreted when written or read
- https://github.com/tradingstrategy-ai/trading-strategy/issues/104
> Workaround pair data issues

- CHANGELOG.md
- tests/test_client.py
- tests/test_lending.py
- tradingstrategy/client.py
- tradingstrategy/lending.py
- tradingstrategy/transport/cache.py
Part of https://github.com/tradingstrategy-ai/trade-executor/issues/497
Support fetching lending candles so `trade-executor` can consume
> Aave candle support

- CHANGELOG.md
- tradingstrategy/pair.py
Allows a fix for test-trade for multipair universes in tradeexecutor
> add exchange_universe argument to get_pair

- tests/test_lending.py
- tradingstrategy/lending.py
Add more info to lending reserve
> More lending reserve info

- tests/test_lending.py
- tradingstrategy/client.py
- tradingstrategy/lending.py
- tradingstrategy/types.py
- tradingstrategy/universe.py
- Add `resolve_lending_reserve()` to look up lending reserves by human description
- Various docstring fixes
> Lending reserve lookup

- tests/test_lending.py
- tradingstrategy/client.py
- tradingstrategy/lending.py
- tradingstrategy/utils/groupeduniverse.py
- Load multiple lending metrics for multiple reserves
> Lending universe manipulation

- tests/test_lending.py
- tradingstrategy/lending.py
Add:
* vToken (variable debt token) info: id, symbol, address, decimals
* Additional details which are relevant for trading: latest LTV, liquidation threshold
> Add more details to lending reserve

- CHANGELOG.md
- tests/test_lending.py
- tradingstrategy/lending.py
- tradingstrategy/pair.py
- Several methods to help lending universe construction
> Adding lending universe filtering methods

- CHANGELOG.md
- pyproject.toml
- tests/test_lending.py
- tradingstrategy/client.py
- tradingstrategy/direct_feed/synthetic_feed.py
- tradingstrategy/direct_feed/trade_feed.py
- tradingstrategy/lending.py
- tradingstrategy/transport/jsonl.py
- tradingstrategy/universe.py
- Add `tqdm` progress bar lending rate download
- Use `tqdm_loggable` everywhere
> Lending rate progress bar

- CHANGELOG.md
- tests/test_candle_data.py
- tests/test_lending.py
- tests/test_pair_by_volume.py
- tests/test_pair_universe.py
- tradingstrategy/candle.py
- tradingstrategy/lending.py
- tradingstrategy/pair.py
- tradingstrategy/stablecoin.py
- tradingstrategy/types.py
- tradingstrategy/utils/format.py
- tradingstrategy/utils/groupeduniverse.py
- tradingstrategy/utils/jupyter.py
- tradingstrategy/utils/time.py
- Allow pair description to set `exchange_slug` to `None` to signal that we do not care about DEX
- Various other API updates
> Find best pair across all dexes and other improvements

- CHANGELOG.md
- tradingstrategy/charting/candle_chart.py
- removes duplicate timestamp from candle labels
> Remove duplicate timestamp from candle labels

- CHANGELOG.md
- tradingstrategy/lending.py
- tradingstrategy/pair.py
- tradingstrategy/universe.py
- Do not allow to construct invalid data universe by a human mistake
> Add more asserts when creating Universe

- CHANGELOG.md
- tests/test_lending.py
- tradingstrategy/lending.py
- Move `estimate_accrued_interes` to `LendingCandleUniverse`
- Better exception handling if no data
- Cover with tests
> Estimate interest

- CHANGELOG.md
- tests/direct_feed/test_filter_wick.py
- tradingstrategy/utils/groupeduniverse.py
> add `remove_zero_candles`

- CHANGELOG.md
- tests/test_binance_data.py
- tradingstrategy/binance/constants.py
- tradingstrategy/chain.py
- tradingstrategy/pair.py
- `DEXPair.exchange_name` is set if `PandasPairUniverse(exchange_universe)` is given
- Add `ChainId.centralised_exchange = -1` id that is used now for Binance loaded data
> Add exchange name as part of the pair

- tests/test_binance_data.py
- tradingstrategy/binance/downloader.py
- tradingstrategy/candle.py
- tradingstrategy/pair.py
- tradingstrategy/utils/groupeduniverse.py
- Doc and function argument updates
- Binance new errors codes and skips for them
> Code ergonomic fixes

- CHANGELOG.md
- tests/test_lending.py
- tradingstrategy/lending.py
Part of https://github.com/tradingstrategy-ai/trade-executor/issues/888
> Add support for Aave v2

- CHANGELOG.md
- tradingstrategy/binance/downloader.py
update to accomodate changes in Binance API for `https://api.binance.com/api/v3/exchangeInfo`
> Binance-spot-fetch-fix

- CHANGELOG.md
- tradingstrategy/binance/downloader.py
Updates progress bar to show individual progress for each asset if less than 5 assets.
> update progress bar

- tradingstrategy/chain.py
> Add new ChainId

- CHANGELOG.md
- tests/test_binance_data.py
- tests/test_candle_universe.py
- tradingstrategy/utils/groupeduniverse.py
useful for resampling dataframes that are not candlestick data e.g. return value from `pandas_ta.bbands`
> add resample dataframe utility method

- CHANGELOG.md
- tradingstrategy/liquidity.py
- tradingstrategy/pair.py
- tradingstrategy/utils/groupeduniverse.py
- There are ~60 broken open price data points for U/ni v3 price feeds, cause unknown 
- Add `fix_bad_wicks(bad_open_close_threshold)` to massage the data
- Add `filter_for_blacklisted_tokens`
> Add bad_open_close_threshold fix for broken open price data points

- CHANGELOG.md
- tests/test_liquidity_universe.py
- tradingstrategy/client.py
- tradingstrategy/liquidity.py
- tradingstrategy/transport/cache.py
- tradingstrategy/types.py
- Add: `Client.fetch_tvl_by_pair_ids` to allow liquidity data loading for selected trading pairs
> Partial tvl load

- CHANGELOG.md
- tests/test_candle_universe.py
- tradingstrategy/exchange.py
- tradingstrategy/liquidity.py
- tradingstrategy/utils/wrangle.py
- Add: `examine_price_between_time_anomalies`- anomaly examination if open/close between days is a strange value
- Add: `fix_prices_in_between_time_frames()`- to heal broken open/close entries caused by MEV bots
- Add: `remove_min_max_price()`: Remove candles where open value is outside the floating point range
> Add anomaly examination if open/close between days is a strange value

- tests/test_top_pairs.py
- tradingstrategy/client.py
- tradingstrategy/stablecoin.py
- tradingstrategy/top.py
- tradingstrategy/transport/cache.py
> Top pairs 

- CHANGELOG.md
- tests/test_candle_universe.py
- tradingstrategy/pair.py
- tradingstrategy/utils/wrangle.py
- Add: `wrangle.normalise_volume` to deal with different volume formats of Uniswap v2 and v3
> Add normalise_volume() helper

- CHANGELOG.md
- scripts/meme-token-basket.py
- tradingstrategy/alternative_data/coingecko.py
- tradingstrategy/liquidity.py
- tradingstrategy/transport/cache.py
- tradingstrategy/utils/token_filter.py
- Handle empty TVL responses better  
- Not a complete fix: some issues with the resulting data still
> Tvl loader fixes

- CHANGELOG.md
- tests/test_coingecko.py
- tests/test_top_pairs.py
- tradingstrategy/client.py
- tradingstrategy/pair.py
- tradingstrategy/top.py
- tradingstrategy/transport/cache.py
> Add /top by token addresses query

- CHANGELOG.md
- tests/test_top_pairs.py
- tradingstrategy/pair.py
- tradingstrategy/top.py
- tradingstrategy/transport/cache.py
- tradingstrategy/utils/schema.py
- tradingstrategy/utils/token_extra_data.py
- Add: `utils.token_extra_data` to load additional trading pair data
- Add: `load_extra_metadata` to load buy and sell tax for given trading pairs
> Load token metadata like buy and sell tax for trading pairs

- .github/workflows/python-app.yml
- CHANGELOG.md
- tests/conftest.py
- tests/test_candle_universe.py
- tradingstrategy/utils/groupeduniverse.py
- tradingstrategy/utils/wrangle.py
- Add: `heal_anomalies` to get rid of MEV anomalies, second attempt - handles anomalies detection and smoothing out better
- Add: `CandleUniverse(autoheal_pair_limit)` and reworked how to mitigate MEV issues on pricing data
> Better alternative way to heal MEV data

- CHANGELOG.md
- tests/conftest.py
- tests/test_candle_universe.py
- tests/test_clmm.py
- tests/test_liquidity_universe.py
- tests/test_resampled_liquidity_universe.py
- tests/test_top_pairs.py
- tradingstrategy/candle.py
- tradingstrategy/client.py
- tradingstrategy/liquidity.py
- tradingstrategy/pair.py
- tradingstrategy/transport/cache.py
- Add: Support for /WETH quoted TVL data loading on Uniswap v3 
- Some test speed optimisation by caching `pairs_df` and default `PandasPairUniverse`
> Adding tvl2 fetch option

- tradingstrategy/universe.py
> Fix liquidity_time_bucket attribute on Universe

- CHANGELOG.md
- tests/test_clmm.py
- tests/test_token_metadata.py
- tradingstrategy/client.py
- tradingstrategy/pair.py
- tradingstrategy/token_metadata.py
- tradingstrategy/transport/cache.py
- tradingstrategy/transport/jsonl.py
- tradingstrategy/utils/logging_retry.py
- tradingstrategy/utils/token_extra_data.py
- Add: `Client.fetch_token_metadata`: Load token metadata for given token addresses, including Coingecko and TokenSniffer data
- Add: `token_extra_data.load_token_metadata`: Load and cache token metadata for given DataFrame of trading pairs
> Token metadata

- CHANGELOG.md
- tests/test_tvl.py
- tradingstrategy/client.py
- tradingstrategy/transport/cache.py
- tradingstrategy/tvl.py
- tradingstrategy/utils/token_filter.py
- Add: `Client.fetch_tvl()` endpoint to stream TVL data efficiently
> Fetch min tvl

- tests/test_lending.py
- tests/transport/test_cache.py
- tradingstrategy/transport/cache.py
- Set ints might be in a random order
> Make sure pair ids in cache filenames are deterministic

- tradingstrategy/data_bundles/preprocessed_backtest.py
- tradingstrategy/transport/cache.py
- tradingstrategy/transport/progress_enabled_download.py
- tradingstrategy/utils/token_filter.py
- First batch of changes
- Includes developer experience updates as well
> Prepared backtest sets

- poetry.lock
- tests/test_token_metadata.py
- tests/test_vault.py
- tradingstrategy/alternative_data/vault.py
- tradingstrategy/chain.py
- tradingstrategy/exchange.py
- tradingstrategy/pair.py
- tradingstrategy/stablecoin.py
- tradingstrategy/utils/token_filter.py
- tradingstrategy/vault.py
- Add the support for vaults and vault universe
> Vault universe

- CHANGELOG.md
- poetry.lock
- pyproject.toml
- tradingstrategy/binance/constants.py
- Update dependency version pindows for Python, PyArrow and others
> Bump dependencies
